### ISSUE TITLE
Test ChosenSpell function

### ISSUE THREAD

**Issue by 0verIords** [go-internship/Hero-Vs-Dragon-Game#4]
I need to test ChosenSpell function/ The problem is there is a input function which prevens me from testing. I need to remove it from the function

**Comment by anatoliyfedorenko** [comment]
@0verIords когда задачу закрываешь, обычно отписываться надо почему закрыл, что сделал. Что в результате имеешь. Пожалуйста напиши обощенный итог работы по задаче

**Comment by 0verIords** [comment]
Это проблемма решена, я разделили функцию ChosenSpell на несколько маленьких, исправил ошибку с функцией check(она не проверяла если пользователь вводит место цифры символы и из-за этого были ошибки которые вызывали бесконечные цикл), теперь статус игры возвращает строку с информацией чтобы легче тестировать. Основные ошибки были в том что функции ничего не возвращали и код был объемный, тестировать было тяжело. Сейчас эта функция и его разделенные функции были протестированы.
